/* AUTO-GENERATED by scripts/build-data.mjs on 2026-09-22 - do not edit by hand.
 * Every number in the video comes from this file, which is computed from
 * ../data/survey_stats.json, ../data/facts.js and ../shared/survey.js. Re-run: npm run data */
export const D = {
  "generatedFrom": [
    "data/survey_stats.json",
    "data/facts.js",
    "shared/survey.js"
  ],
  "factsChecked": "2026-09-22",
  "meta": {
    "respondents": 200,
    "questions": 104,
    "title": "Social Acceptance of Sustainable Data Centres in Ireland",
    "source": "Maynooth University survey of people in Ireland (supplied for the BU Induction Hack 2026)",
    "minCell": 3
  },
  "cso": {
    "source": "Central Statistics Office (CSO), Data Centres Metered Electricity Consumption 2025",
    "url": "https://www.cso.ie/en/releasesandpublications/ep/p-dcmec/datacentresmeteredelectricityconsumption2025/keyfindings/",
    "years": [
      {
        "year": 2015,
        "pct": 5
      },
      {
        "year": 2016,
        "pct": 6
      },
      {
        "year": 2017,
        "pct": 7
      },
      {
        "year": 2018,
        "pct": 8
      },
      {
        "year": 2019,
        "pct": 9
      },
      {
        "year": 2020,
        "pct": 11
      },
      {
        "year": 2021,
        "pct": 14
      },
      {
        "year": 2022,
        "pct": 18
      },
      {
        "year": 2023,
        "pct": 21
      },
      {
        "year": 2024,
        "pct": 22
      },
      {
        "year": 2025,
        "pct": 23
      }
    ],
    "first": {
      "year": 2015,
      "pct": 5
    },
    "last": {
      "year": 2025,
      "pct": 23
    },
    "urbanHomes": 18,
    "allHomes": 28,
    "ruralHomes": 9,
    "projection2034": 31
  },
  "support": {
    "pct": 56,
    "raw": 55.5,
    "n": 198
  },
  "opposed": {
    "pct": 22,
    "n": 198
  },
  "accept5km": {
    "pct": 30,
    "raw": 30.2,
    "n": 195
  },
  "fossil": {
    "statement": "All data centres in Ireland run on fossil fuels",
    "verdictTag": "False",
    "short": "They run on the national grid, and about 41% of Irish electricity was renewable in 2024.",
    "sourceLabel": "SEAI - Renewables statistics (RES-E 41.3% in 2024)",
    "sourceUrl": "https://www.seai.ie/data-and-insights/seai-statistics/renewables",
    "n": 195,
    "true": 52,
    "false": 29,
    "dontKnow": 20,
    "rawTrue": 51.8,
    "rawFalse": 28.7,
    "rawDontKnow": 19.5
  },
  "renewables": {
    "pct": 41.3,
    "year": 2024,
    "source": "SEAI",
    "url": "https://www.seai.ie/data-and-insights/seai-statistics/renewables",
    "text": "Renewables supplied 41.3% of Ireland's electricity in 2024; the 2030 target is 80%."
  },
  "paradox": [
    {
      "label": "Nothing at all",
      "pct": 46,
      "raw": 46.42857142857143,
      "n": 28,
      "small": true
    },
    {
      "label": "Very little",
      "pct": 51,
      "raw": 50.98039215686274,
      "n": 51,
      "small": false
    },
    {
      "label": "A moderate amount",
      "pct": 40,
      "raw": 39.6551724137931,
      "n": 58,
      "small": false
    },
    {
      "label": "Quite a lot",
      "pct": 57,
      "raw": 56.75675675675676,
      "n": 37,
      "small": false
    },
    {
      "label": "A great deal",
      "pct": 90,
      "raw": 90,
      "n": 20,
      "small": true
    }
  ],
  "greatDeal": {
    "label": "A great deal",
    "pct": 90,
    "raw": 90,
    "n": 20,
    "small": true
  },
  "greatDealQ24": {
    "pct": 74,
    "raw": 73.6842105263158,
    "n": 19
  },
  "room": [
    {
      "value": 1,
      "label": "Completely unacceptable",
      "count": 17
    },
    {
      "value": 2,
      "label": "Somewhat unacceptable",
      "count": 19
    },
    {
      "value": 3,
      "label": "Neither acceptable nor unacceptable",
      "count": 34
    },
    {
      "value": 4,
      "label": "Somewhat acceptable",
      "count": 21
    },
    {
      "value": 5,
      "label": "Completely acceptable",
      "count": 9
    }
  ],
  "conds": [
    {
      "id": "q78",
      "short": "Renewable power",
      "rating": 36.4,
      "ratingPct": 36,
      "pick": 48.7,
      "pickPct": 49,
      "rRank": 10,
      "pRank": 2,
      "nRating": 181
    },
    {
      "id": "q79",
      "short": "Waste heat for homes",
      "rating": 38.7,
      "ratingPct": 39,
      "pick": 54.4,
      "pickPct": 54,
      "rRank": 9,
      "pRank": 1,
      "nRating": 181
    },
    {
      "id": "q80",
      "short": "Community fund",
      "rating": 41.5,
      "ratingPct": 42,
      "pick": 39,
      "pickPct": 39,
      "rRank": 7,
      "pRank": 4,
      "nRating": 176
    },
    {
      "id": "q81",
      "short": "Local jobs quota",
      "rating": 42.8,
      "ratingPct": 43,
      "pick": 40.5,
      "pickPct": 41,
      "rRank": 4,
      "pRank": 3,
      "nRating": 182
    },
    {
      "id": "q82",
      "short": "Independent monitoring",
      "rating": 45.2,
      "ratingPct": 45,
      "pick": 24.6,
      "pickPct": 25,
      "rRank": 2,
      "pRank": 5,
      "nRating": 177
    },
    {
      "id": "q83",
      "short": "Landscape-friendly design",
      "rating": 42.5,
      "ratingPct": 43,
      "pick": 24.6,
      "pickPct": 25,
      "rRank": 5,
      "pRank": 6,
      "nRating": 174
    },
    {
      "id": "q84",
      "short": "Open days",
      "rating": 39.3,
      "ratingPct": 39,
      "pick": 14.9,
      "pickPct": 15,
      "rRank": 8,
      "pRank": 7,
      "nRating": 178
    },
    {
      "id": "q85",
      "short": "STEM in local schools",
      "rating": 42,
      "ratingPct": 42,
      "pick": 13.3,
      "pickPct": 13,
      "rRank": 6,
      "pRank": 8,
      "nRating": 181
    },
    {
      "id": "q86",
      "short": "Lower local bills",
      "rating": 50,
      "ratingPct": 50,
      "pick": 12.8,
      "pickPct": 13,
      "rRank": 1,
      "pRank": 9,
      "nRating": 170
    },
    {
      "id": "q87",
      "short": "Liaison committee",
      "rating": 44,
      "ratingPct": 44,
      "pick": 7.2,
      "pickPct": 7,
      "rRank": 3,
      "pRank": 10,
      "nRating": 184
    }
  ],
  "nPick": 195,
  "mismatch": {
    "pickedMore": "q78",
    "ratedMore": "q86"
  },
  "samplePackage": [
    "q79",
    "q81",
    "q82"
  ],
  "sampleVote": {
    "convNeither": 27,
    "convSomewhat": 7,
    "accepting": 64
  },
  "nearby": {
    "yes": {
      "pct": 29,
      "raw": 28.82882882882883,
      "n": 111
    },
    "no": {
      "pct": 39,
      "raw": 39.285714285714285,
      "n": 56
    }
  },
  "strongSupp": {
    "pct": 38,
    "raw": 38.297872340425535,
    "n": 47
  },
  "bias": {
    "q62": {
      "id": "q62",
      "text": "My first impression of data centres — before I read any detailed information — has stayed with me",
      "n": 190,
      "agree": 25,
      "neither": 22,
      "disagree": 53,
      "options": [
        {
          "label": "Strongly Disagree",
          "pct": 24.2
        },
        {
          "label": "Disagree",
          "pct": 28.9
        },
        {
          "label": "Neither",
          "pct": 22.1
        },
        {
          "label": "Agree",
          "pct": 13.7
        },
        {
          "label": "Strongly Agree",
          "pct": 11.1
        }
      ]
    },
    "q65": {
      "id": "q65",
      "text": "I tend to trust the first source of information I encounter on a topic like data centres",
      "n": 192,
      "agree": 29,
      "neither": 21,
      "disagree": 51,
      "options": [
        {
          "label": "Strongly Disagree",
          "pct": 23.4
        },
        {
          "label": "Disagree",
          "pct": 27.1
        },
        {
          "label": "Neither",
          "pct": 20.8
        },
        {
          "label": "Agree",
          "pct": 17.7
        },
        {
          "label": "Strongly Agree",
          "pct": 10.9
        }
      ]
    },
    "q55": {
      "id": "q55",
      "text": "News stories about data centres using excessive energy have strongly shaped my views",
      "n": 186,
      "agree": 37,
      "neither": 15,
      "disagree": 48,
      "options": [
        {
          "label": "Strongly Disagree",
          "pct": 14.5
        },
        {
          "label": "Disagree",
          "pct": 33.9
        },
        {
          "label": "Neither",
          "pct": 15.1
        },
        {
          "label": "Agree",
          "pct": 21.5
        },
        {
          "label": "Strongly Agree",
          "pct": 15.1
        }
      ]
    },
    "q57": {
      "id": "q57",
      "text": "The information I have encountered about data centres has mostly been negative",
      "n": 185,
      "agree": 36,
      "neither": 20,
      "disagree": 44,
      "options": [
        {
          "label": "Strongly Disagree",
          "pct": 17.8
        },
        {
          "label": "Disagree",
          "pct": 26.5
        },
        {
          "label": "Neither",
          "pct": 20
        },
        {
          "label": "Agree",
          "pct": 20
        },
        {
          "label": "Strongly Agree",
          "pct": 15.7
        }
      ]
    },
    "q59": {
      "id": "q59",
      "text": "If my local community opposed a data centre development, I would also oppose it",
      "n": 183,
      "agree": 33,
      "neither": 18,
      "disagree": 50,
      "options": [
        {
          "label": "Strongly Disagree",
          "pct": 26.2
        },
        {
          "label": "Disagree",
          "pct": 23.5
        },
        {
          "label": "Neither",
          "pct": 17.5
        },
        {
          "label": "Agree",
          "pct": 21.3
        },
        {
          "label": "Strongly Agree",
          "pct": 11.5
        }
      ]
    },
    "q61": {
      "id": "q61",
      "text": "Public protests against data centres have influenced my own views",
      "n": 189,
      "agree": 28,
      "neither": 23,
      "disagree": 49,
      "options": [
        {
          "label": "Strongly Disagree",
          "pct": 23.3
        },
        {
          "label": "Disagree",
          "pct": 25.4
        },
        {
          "label": "Neither",
          "pct": 23.3
        },
        {
          "label": "Agree",
          "pct": 15.3
        },
        {
          "label": "Strongly Agree",
          "pct": 12.7
        }
      ]
    }
  },
  "water": {
    "text": "Data centres on the public water network use under 0.3% of the drinking water Uisce Éireann supplies - but use nearly doubled in the dry July of 2026 (over 200 million litres that month).",
    "source": "Uisce Éireann via TheJournal.ie",
    "url": "https://www.thejournal.ie/ireland-data-centre-water-use-7137959-Aug2026/",
    "share": 0.3
  },
  "officialSources": [
    {
      "name": "CSO",
      "what": "electricity 2015-2025",
      "url": "https://www.cso.ie/en/releasesandpublications/ep/p-dcmec/datacentresmeteredelectricityconsumption2025/keyfindings/"
    },
    {
      "name": "SEAI",
      "what": "renewables",
      "url": "https://www.seai.ie/data-and-insights/seai-statistics/renewables"
    },
    {
      "name": "EirGrid",
      "what": "wind curtailment",
      "url": "https://cms.eirgrid.ie/sites/default/files/publications/Annual-Renewable-Constraint-and-Curtailment-Report-2024-V1.0.pdf"
    },
    {
      "name": "CRU",
      "what": "grid policy",
      "url": "https://www.cru.ie/about-us/news/the-cru-publishes-its-decision-on-new-electricity-connection-policy-for-data-centres/"
    },
    {
      "name": "IEA",
      "what": "global demand",
      "url": "https://www.iea.org/reports/energy-and-ai/energy-demand-from-ai"
    },
    {
      "name": "Uisce Éireann",
      "what": "water",
      "url": "https://www.thejournal.ie/ireland-data-centre-water-use-7137959-Aug2026/"
    }
  ],
  "counts": {
    "facts": 18,
    "claims": 18,
    "policies": 8,
    "trueFalse": 8
  }
} as const;
