/*
 * survey.js - tiny read-only helper over window.SURVEY_STATS (generated by tools/extract_survey.py).
 * Load order in a page:  <script src="../../data/survey_stats.js"></script>
 *                        <script src="../../shared/survey.js"></script>
 *
 * Everything here works on AGGREGATE counts. There are no individual responses in the data.
 *
 * Question shape: { id, text, group, item, kind, themes, n_answered, ordered, options: [...] }
 *   kind: 'single' | 'truefalse' | 'multi' | 'scale_numeric' | 'numeric'
 *   options: [{ label, short, value, count, pct }] - pct is % of people who answered that question.
 *   Ordered questions list options low -> high and give each a 1-based `value`
 *   (5-point agree scales: 1 Strongly Disagree ... 5 Strongly Agree; `short` drops the "(n)" suffix).
 *   True/false items (q18-q25) have options 'True', 'False', "Don't know".
 *   Multi-select questions (q16, q52, q53, q88): percentages can sum to more than 100.
 */
(function () {
  const S = window.SURVEY_STATS;
  if (!S) {
    document.addEventListener('DOMContentLoaded', () => {
      document.body.innerHTML =
        '<div style="font:16px/1.5 system-ui;max-width:560px;margin:15vh auto;padding:24px">' +
        '<h1 style="font-size:22px">Survey data not found</h1>' +
        '<p>Run <code>python3 tools/extract_survey.py</code> from the project folder, then reload this page.</p></div>';
    });
    return;
  }

  const byId = {};
  S.questions.forEach((q) => { byId[q.id] = q; });
  const xt = {};
  S.crosstabs.forEach((c) => { xt[c.by + '>' + c.of] = c; });

  const toPred = (m) => {
    if (typeof m === 'function') return m;
    if (m instanceof RegExp) return (o) => m.test(o.label);
    if (Array.isArray(m)) return (o) => m.includes(o.label) || m.includes(o.short);
    return (o) => o.label === m || o.short === m;
  };
  const isAgree = (o) => o.value === 4 || o.value === 5;
  const isDisagree = (o) => o.value === 1 || o.value === 2;
  const isNeutral = (o) => o.value === 3;

  const Survey = {
    meta: S.meta,
    n: S.meta.respondents,
    questions: S.questions,

    /** Question by id ('q18'). Throws if missing so mistakes show up immediately. */
    q(id) {
      const q = byId[id];
      if (!q) throw new Error('Unknown survey question ' + id);
      return q;
    },

    /** First question whose full text matches the regex (or null). */
    find(re) {
      return S.questions.find((q) => re.test(q.text)) || null;
    },

    /** Short human label: the bracketed matrix item if there is one, else the question text. */
    label(id) {
      const q = Survey.q(id);
      return q.item || q.text;
    },

    /** Percentage (0-100, of people who answered) choosing options matching m (label, [labels], RegExp or fn). */
    pct(id, m) {
      const pred = toPred(m);
      return Survey.q(id).options.filter(pred).reduce((s, o) => s + o.pct, 0);
    },

    /** Headcount choosing options matching m. */
    count(id, m) {
      const pred = toPred(m);
      return Survey.q(id).options.filter(pred).reduce((s, o) => s + o.count, 0);
    },

    /** 5-point agree scales: % agree (4+5), % disagree (1+2), % neither (3). */
    agree: (id) => Survey.pct(id, isAgree),
    disagree: (id) => Survey.pct(id, isDisagree),
    neutral: (id) => Survey.pct(id, isNeutral),

    /** Mean score for ordered questions (null if not ordered). */
    mean: (id) => (Survey.q(id).mean ?? null),

    /**
     * Cross-tab of question `of` split by the answers to question `by`.
     * Returns rows [{label, short, n, cells:[{label, short, count, pct}]}]; n or count are null when
     * suppressed (fewer than meta.min_cell people). Returns null if that cross-tab was not generated.
     */
    crosstab(by, of) {
      const c = xt[by + '>' + of];
      if (!c) return null;
      const A = Survey.q(by).options;
      const B = Survey.q(of).options;
      return A.map((a, i) => ({
        label: a.label,
        short: a.short || a.label,
        value: a.value,
        n: c.group_n[i],
        cells: B.map((b, j) => {
          const count = c.counts[i][j];
          const n = c.group_n[i];
          return {
            label: b.label,
            short: b.short || b.label,
            value: b.value,
            count,
            pct: count == null || !n ? null : (100 * count) / n,
          };
        }),
      }));
    },

    /**
     * Within the group of people who answered `byMatch` to question `by`, the % choosing `ofMatch` on `of`.
     * Returns {pct, n} or null when the group or any matching cell is suppressed.
     */
    within(by, byMatch, of, ofMatch) {
      const rows = Survey.crosstab(by, of);
      if (!rows) return null;
      const bp = toPred(byMatch);
      const op = toPred(ofMatch);
      const row = rows.find((r) => bp(r));
      if (!row || !row.n) return null;
      let sum = 0;
      for (const cell of row.cells) {
        if (!op(cell)) continue;
        if (cell.count == null) return null;
        sum += cell.count;
      }
      return { pct: (100 * sum) / row.n, n: row.n };
    },

    /** Round for display: 54.6 -> "55%". */
    fmt: (p) => (p == null ? '–' : Math.round(p) + '%'),

    /** Out of 200-style headcount for dot/people visualisations. */
    people(id, m) {
      return Math.round((Survey.pct(id, m) / 100) * Survey.q(id).n_answered);
    },

    predicates: { isAgree, isDisagree, isNeutral },
  };

  window.Survey = Survey;
})();
